# -*- coding: utf-8 -*-
"""linear_reg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cd6I0MRFCuRqIsroIBvK-wmnvPrCnf8O
"""

import numpy
from pandas import read_csv
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression

data = read_csv('linear_reg.csv')

# plot scatter
plt.scatter(data.income,data.expenditure)

data.corr()

model = LinearRegression()

X_train = data[['income']]
Y_train = data[['expenditure']]

# Model training
model.fit(X_train,Y_train)
model.score(X_train,Y_train)

# prediction based on trained model
model.predict([[60],[70]])

# check intercept
a = model.intercept_[0]

# get params
b = model.coef_[0][0]
a + b*numpy.array([60,70])

# plot scatter after training
plt.scatter(data.income,data.expenditure, color = 'green', label = 'train data')

# depict the best fit line
Y_train_pred = model.predict(X_train)
plt.plot(X_train, Y_train_pred, color = 'black', label = 'best line')

# output
plt.legend(loc = 2)
plt.show()